LimsFilter <- function(data_to_filter){
	       ##################################################
	       ############   Variables Selection  ##############
           ##################################################

	# Comment out varibles that you want to see after filering. 
	# All those variables that are not commented will be filtered out 
    #            [KEY]
	# Commented : Active variable
	# Not Commented out : Deactivated variable 
	#			 [!IMPORTANT]
	# NB : if you deactivate a commented out [which is in an activate state] variable you must also remove 
	#      that variable from the 'LimsEasyRead' fuction

	variables <- c(
	#		"PatientUID",
	#		"Firstname",
	#   	"Surname",
	#		"Gender",
	#		"BirthDate",
	#		"ConsentSMS",
	#		"Analyses_0_Result",
	#		"Analyses_0_ResultCaptureDate",
	#		"Analyses_0_DateAnalysisPublished",
	#		"Analyses_0_DateReceived",
	#		"Analyses_0_review_state",
	#		"Analyses_0_Unit",
	#		"Analyses_0_creation_date",
	#		"ReasonForVLtest",
	#		"VLBreastFeeding",
	#		"VLPoorAdherence",
	#		"VLPregnant",
	#		"VLTreatmentHistory_0_Drug",
	#		"VLTreatmentHistory_0_Treatment",
	#		"VLTreatmentHistory_1_Drug",
	#		"VLTreatmentHistory_2_Drug",
	#  		"Client.x",
		"ReasonForVLtestView",
		"Analyses_0_Retested",
		"Fullname",
	    "Analyses_0_ClientTitle",
		"Date.x",
		"Analyses_0_ClientUID",
		"Analyses_0_DueDate",
		"Analyses_0_Duration",
		"Analyses_0_Earliness",
		"DatePublished",
		"DateReceived",
		"AllowResultsDistribution",
		"Anonymous",
		"BirthDateEstimated",
		"BirthPlace",
		"ClientPatientID.x",
		"CountryState_country",
		"DefaultResultsDistribution",
		"Ethnicity_Obj",
		"Ethnicity_Obj_uid",
		"GuarantorFirstname",
		"GuarantorMobilePhone",
		"GuarantorPostalAddress",
		"GuarantorSurname",
		"HomePhone",
		"InvoiceToInsuranceCompany",
		"LastResultAndTest_0_LastResults.x",
		"LastResultAndTest_0_LastTest.x",
		"MenstrualStatus_0_Hysterectomy",
		"MenstrualStatus_0_OvariesRemoved",
		"MenstrualStatus_0_OvariesRemovedNum",
		"MobilePhone",
		"PatientAsGuarantor",
		"PatientID.x",
		"PhysicalAddress_country",
		"PostalAddress_country",
		"PrimaryReferrer",
		"PrimaryReferrerTitle",
		"PrimaryReferrerUID",
		"PrimaryReferrer_uid",
		"PublicationAttachmentsPermitted",
		"Salutation",
		"Title.x",
		"TreatmentHistory_0_Drug",
		"TreatmentHistory_0_Treatment",
		"TreatmentHistory_1_Drug",
		"TreatmentHistory_2_Drug",
		"Type.x",
		"creation_date.x",
		"creators_0.x",
		"effectiveDate.x",
		"getClientPatientID",
		"getPatientID",
		"getPrimaryReferrerUID",
		"id.x",
		"inactive_state",
		"language.x",
		"modification_date.x",
		"path.x",
		"portal_type.x",
		"review_state.x",
		"sortable_title",
		"title.x",
		"transitions_0_id.x",
		"transitions_0_title.x",
		"AdHoc",
		"Analyses_0_Analyst",
		"Analyses_0_Attachment_0",
		"Analyses_0_Attachment_uid_0",
		"Analyses_0_CategoryTitle",
		"Analyses_0_CategoryUID",
		"Analyses_0_ClientOrderNumber",
		"Analyses_0_Instrument",
		"Analyses_0_InstrumentValid",
		"Analyses_0_Instrument_uid",
		"Analyses_0_IsReflexAnalysis",
		"Analyses_0_Keyword",
		"Analyses_0_MaxTimeAllowed_days",
		"Analyses_0_MaxTimeAllowed_hours",
		"Analyses_0_MaxTimeAllowed_minutes",
		"Analyses_0_PointOfCapture",
		"Analyses_0_ReflexRuleAction",
		"Analyses_0_ReflexRuleActionLevel",
		"Analyses_0_ReportDryMatter",
		"Analyses_0_RequestID",
		"Analyses_0_SamplePartition",
		"Analyses_0_SamplePartition_uid",
		"Analyses_0_SampleTypeUID",
		"Analyses_0_Service",
		"Analyses_0_ServiceTitle",
		"Analyses_0_ServiceUID",
		"Analyses_0_Service_uid",
		"Analyses_0_UID",
		"Analyses_0_cancellation_state",
		"Analyses_0_creators_0",
		"Analyses_0_getRequestID",
		"Analyses_0_id",
		"Analyses_0_language",
		"Analyses_0_modification_date",
		"Analyses_0_portal_type",
		"Analyses_0_sortable_title",
		"Analyses_0_transitions_0_id",
		"Analyses_0_transitions_0_title",
		"Analyses_0_transitions_1_id",
		"Analyses_0_Title",
		"Analyses_0_Type",
		"Analyses_0_transitions_1_title",
		"ClientOrderNumber",
		"ClientPatientID.y",
		"ClientReference",
		"ClientSampleID",
		"ClientUID",
		"Client_uid.x",
		"Composite",
		"Contact",
		"ContactUID",
		"Contact_uid",
		"Creator.x",
		"Description.y",
		"InvoiceExclude",
		"Invoiced",
		"MemberDiscount",
		"PanicEmailAlertToClientSent",
		"Patient.x",
		"PatientID.y",
		"Patient_uid",
		"Priority",
		"Priority_uid",
		"ReportDryMatter",
		"RequestID",
		"Sample",
		"SampleID",
		"SampleType",
		"SampleTypeTitle",
		"SampleType_uid",
		"SampleUID",
		"Sample_uid",
		"Title.y",
		"Type.y",
		"UID.x",
		"cmf_uid.x",
		"creation_date.y",
		"creators_0.y",
		"getId.x",
		"id.y",
		"is_folderish.x",
		"language.y",
		"meta_type.x",
		"modification_date.y",
		"path.y",
		"portal_type.y",
		"review_state.y",
		"transitions_0_id.y",
		"transitions_0_title.y",
		"transitions_1_id.x",
		"transitions_1_title.x",
		"transitions_2_id",
		"transitions_2_title",
		"transitions_3_id",
		"transitions_3_title",
		"Client.y",
		"ClientBatchID",
		"ClientPatientID",
		"Client_uid.y",
		"Creator.y",
		"Date.y",
		"EIDMotherHIVTested",
		"LastResultAndTest_0_LastResults.y",
		"LastResultAndTest_0_LastTest.y",
		"OnsetDateEstimated",
		"Patient.y",
		"Title",
		"Type",
		"UID.y",
		"cmf_uid.y",
		"constrainTypesMode",
		"creation_date",
		"creators_0",
		"excludeFromNav",
		"getId.y",
		"id",
		"immediatelyAddableTypes_0",
		"is_folderish.y",
		"language",
		"locallyAllowedTypes_0",
		"meta_type.y",
		"modification_date",
		"nextPreviousEnabled",
		"path",
		"portal_type",
		"review_state",
		"transitions_0_id",
		"transitions_0_title",
		"transitions_1_id.y",
		"transitions_1_title.y"
	)
	
	# FILTERING
	filter <- names(data_to_filter) %in% variables
	filtered <- data_to_filter[!filter]
	return(filtered)
}
