LimsFilter <- function(data_to_filter){
	       ##################################################
	       ############   Variables Selection  ##############
           ##################################################

	# Comment out varibles that you want to see after filering. 
	# All those variables that are not commented will be filtered out 
    #            [KEY]
	# Commented : Active variable
	# Not Commented out : Deactivated variable 
	#			 [!IMPORTANT]
	# NB : if you deactivate a commented out [which is in an activate state] variable you must also remove 
	#      that variable from the 'LimsEasyRead' fuction

	variables <- c(
			# will used with cases please checkagain and correct
			# "ReasonForVLtest",
			# "VLBreastFeeding",
			# "VLPoorAdherence",
			# "VLPregnant",
			# "VLTreatmentHistory_0_Drug",
			# "VLTreatmentHistory_0_Treatment",
			# "VLTreatmentHistory_1_Drug",
			# "VLTreatmentHistory_2_Drug",
	 	    # "Client.x",
################
	    #   "Patient_uid",	
		#	"BirthDate",
		#	"ConsentSMS",
		#	"Firstname",
		#	"Gender",
	    #   "ClientTitle",
	    #   "Analyses.0.Result",
	    #   "Analyses.0.review_state",
	    #   "Analyses.0.DateReceived",
	    #   "Analyses.0.DateAnalysisPublished",
		#	"Client",
		#	"Surname",
		#	"Analyses.0.Unit",
		#	"Analyses.0.creation_date",
		#   "Analyses.0.ResultCaptureDate",
			"x",	
			"Age",
			"ge.Yrs",
			"ge.MonthDays",
			"BirthDateEstimated",
			"ClientPatientID.x",
			"Country",
			"CountryState_address",
			"CountryState_city",
			"CountryState_country",
			"CountryState_district",
			"CountryState_state",
			"CountryState_zip",
			"DefaultResultsDistribution",
			"Department",
			"District",
			"EmailAddress",
			"Ethnicity",
			"Ethnicity_Obj",
			"Ethnicity_Obj_uid",
			"FathersName",
			"Feature",
			"Fullname",
			"GuarantorBusinessPhone",
			"GuarantorFirstname",
			"GuarantorHomePhone",
			"GuarantorID",
			"GuarantorMobilePhone",
			"GuarantorPostalAddress",
			"GuarantorSurname",
			"HomePhone",
			"InsuranceCompany",
			"InsuranceNumber",
			"InvoiceToInsuranceCompany",
			"JobTitle",
			"LastResultAndTest_0_LastResults",
			"LastResultAndTest_0_LastTest",
			"LastResultAndTest_0_value",
			"MenstrualStatus_0_Hysterectomy",
			"MenstrualStatus_0_HysterectomyYear",
			"MenstrualStatus_0_OvariesRemoved",
			"MenstrualStatus_0_OvariesRemovedNum",
			"MenstrualStatus_0_OvariesRemovedYear",
			"Middleinitial",
			"Middlename",
			"MobilePhone",
			"MothersName",
			"NumberOfSamples",
			"NumberOfSamplesCancelled",
			"NumberOfSamplesOngoing",
			"NumberOfSamplesPublished",
			"ObjectWorkflowStates_inactive_state",
			"ObjectWorkflowStates_review_state",
			"PatientAsGuarantor",
			"PatientID.x",
			"PatientIdentifiersStr",
			"PatientIdentifiers_0_IdentifierType",
			"PatientIdentifiers_0_value",
			"Photo",
			"PhysicalAddress_address",
			"PhysicalAddress_city",
			"PhysicalAddress_country",
			"PhysicalAddress_district",
			"PhysicalAddress_state",
			"PhysicalAddress_zip",
			"PostalAddress_address",
			"PostalAddress_city",
			"PostalAddress_country",
			"PostalAddress_district",
			"PostalAddress_state",
			"PostalAddress_zip",
			"PostalCode",
			"PrimaryReferrer",
			"PrimaryReferrerID",
			"PrimaryReferrerTitle",
			"PrimaryReferrerUID",
			"PrimaryReferrerURL",
			"PrimaryReferrer_uid",
			"PublicationAttachmentsPermitted",
			"RatioOfSamplesOngoing",
			"Remarks.x",
			"Salutation",
			"TreatmentHistory_0_Drug",
			"TreatmentHistory_0_End",
			"TreatmentHistory_0_Start",
			"TreatmentHistory_0_Treatment",
			"TreatmentHistory_0_value",
			"TreatmentHistory_1_Drug",
			"TreatmentHistory_1_value",
			"TreatmentHistory_2_Drug",
			"TreatmentHistory_2_value",
			"Username",
			"allowDiscussion.x",
			"creation_date.x",
			"creators_0",
			"description.x",
			"effectiveDate.x",
			"expirationDate.x",
			"getPatientID",
			"getPrimaryReferrerUID",
			"id.x",
			"inactive_state",
			"language.x",
			"location.x",
			"modification_date.x",
			"path.x",
			"review_state.x",
			"rights.x",
			"title.x",
			"transitions_0_id",
			"transitions_0_title",
			"SampleTypeTitle",
			"transitions.0.id",
			"transitions.0.title",
			"transitions.1.id",
			"transitions.1.title",
			"transitions.2.id",
			"transitions.2.title",
			"transitions.3.id",
			"transitions.3.title",
			"Doctor",
			"getSampleUID",
			"PublicationSpecification",
			"StorageLocationUID",
			"SampleID",
			"AnalysesNum.0",
			"AnalysesNum.1",
			"Priority_uid",
			"ResultsInterpretation",
			"Template",
			"Sampler",
			"ContactUID",
			"BatchURL",
			"SampleURL",
			"ContactFullName",
			"ScheduledSamplingSampler",
			"TemplateUID",
			"UID",
			"ClientSampleID",
			"title.y",
			"Composite",
			"MemberDiscount",
			"AdHoc",
			"SamplerFullName",
			"CCEmails",
			"DatePublished",
			"ContactEmail",
			"CreatorEmail",
			"ClientOrderNumber",
			"SampleType_uid",
			"ReceivedBy",
			"PatientUID",
			"TemplateURL",
			"SubGroup",
			"SamplerEmail",
			"SampleType",
			"Batch",
			"PreparationWorkflow",
			"Analyses.0.Service",
			"Analyses.0.Title",
			"Analyses.0.cancellation_state",
			"ses.0.Attachment.0",
			"ses.0.Method",
			"ses.0.ReflexAnalysisOf",
			"ses.0.UID",
			"ses.0.title",
			"ses.0.Verificators",
			"ses.0.ReflexRuleLocalID",
			"ses.0.ServiceUID",
			"ses.0.InstrumentUID",
			"ses.0.location",
			"ses.0.IsReflexAnalysis",
			"ses.0.Analyst",
			"ses.0.ClientOrderNumber",
			"ses.0.InstrumentValid",
			"ses.0.Keyword",
			"Analyses.0.NumberOfRequiredVerifications",
			"Analyses.0.portal_type",
			"Analyses.0.DetectionLimitOperand",
			"Analyses.0.OriginalReflexedAnalysis",
			"Analyses.0.SamplePartition_uid",
			"Analyses.0.language",
			"Analyses.0.ReflexRuleActionsTriggered",
			"Analyses.0.rights",
			"Analyses.0.Calculation",
			"Analyses.0.RequestID",
			"Analyses.0.allowDiscussion",
			"Analyses.0.Earliness",
			"Analyses.0.getRequestID",
			"Analyses.0.expirationDate",
			"Analyses.0.MethodUID",
			"Analyses.0.CategoryUID",
			"Analyses.0.Instrument",
			"Analyses.0.ResultDM",
			"Analyses.0.PointOfCapture",
			"Analyses.0.Type",
			"Analyses.0.id",
			"Analyses.0.transitions.0.id",
			"Analyses.0.transitions.0.title",
			"Analyses.0.transitions.1.id",
			"Analyses.0.transitions.1.title",
			"Analyses.0.Description",
			"Analyses.0.modification_date",
			"Analyses.0.DateSampled",
			"Analyses.0.SampleTypeUID",
			"Analyses.0.SamplePartition",
			"Analyses.0.Service_uid",
			"Analyses.0.Instrument_uid",
			"Analyses.0.Remarks",
			"Analyses.0.DueDate",
			"Analyses.0.Retested",
			"Analyses.0.SamplePointUID",
			"Analyses.0.description",
			"Analyses.0.Uncertainty",
			"Analyses.0.ReportDryMatter",
			"Analyses.0.CanMethodBeChanged",
			"Analyses.0.MaxTimeAllowed.hours",
			"Analyses.0.MaxTimeAllowed.minutes",
			"Analyses.0.MaxTimeAllowed.days",
			"Analyses.0.effectiveDate",
			"Analyses.0.ReflexRuleAction",
			"Analyses.0.ClientUID",
			"Analyses.0.sortable_title",
			"Analyses.0.ClientTitle",
			"Analyses.0.Duration",
			"Analyses.0.Attachment_uid.0",
			"Analyses.0.creators.0",
			"description.y",
			"Sample_uid",
			"SamplePointTitle",
			"Creator",
			"rights.y",
			"SamplingDeviation",
			"getSampler",
			"DateReceived",
			"SamplingRoundUID",
			"RequestID",
			"Invoice",
			"allowDiscussion.y",
			"path.y",
			"getClientSampleID",
			"expirationDate.y",
			"ClientURL",
			"StorageLocation",
			"SamplePoint",
			"Specification",
			"ClientReference",
			"DateVerified",
			"creation_date.y",
			"Priority",
			"getSampleID",
			"getPrinted",
			"ContactUsername",
			"ClientPatientID.y",
			"InvoiceExclude",
			"id.y",
			"getDateSampled",
			"Patient",
			"BatchUID",
			"effectiveDate.y",
			"DateSampled",
			"getId",
			"SampleTypeUID",
			"BatchID",
			"SampleCondition",
			"SamplingRound",
			"Printed",
			"Remarks.y",
			"TemplateTitle",
			"review_state.y",
			"Profile",
			"ParentAnalysisRequest",
			"SamplePointUID",
			"getDatePublished",
			"location.y",
			"SampleUID",
			"DefaultContainerType",
			"SamplingDate",
			"Contact",
			"Contact_uid",
			"PanicEmailAlertToClientSent",
			"ChildAnalysisRequest",
			"CreatorFullName",
			"modification_date.y",
			"getClientUID",
			"EnvironmentalConditions",
			"language.y",
			"ReportDryMatter",
			"ClientUID",
			"getDateVerified",
			"Client_uid",
			"PatientID.y",
			"Sample",
			"getBatchUID",
			"getPatientUID",
			"creators.0",
			"Invoiced",
			"X",
			"X.1",
			"X.2",
			"X.3",
			"X.4",
			"X.5",
			"X.6",
			"X.7",
			"X.8",
			"X.9",
			"X.10",
			"X.11",
			"X.12",
			"X.13",
			"X.14",
			"X.15",
			"X.16",
			"X.17",
			"X.18",
			"X.19",
			"X.20",
			"X.21",
			"X.22",
			"X.23",
			"X.24",
			"X.25",
			"X.26",
			"X.27",
			"X.28",
			"X.29",
			"X.30",
			"X.31"

	)
	
	# FILTERING
	filter <- names(data_to_filter) %in% variables
	filtered <- data_to_filter[!filter]
	return(filtered)
}
